### ISSUE TITLE
Infografía-Lenguajes de programación

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Brisa-4#1]
[Infografía_Leng. de programación.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Brisa-4/files/8586624/Infografia_Leng.de.programacion.pdf)

**Comment by Rosa218** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
